In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [14]:
df=pd.read_csv("decathlon_clean.csv")

In [15]:
df

,product_name,brand,star_rating,MRP(in rs),sale_price(in rs),Quantity,amount,transaction_Id,transaction date,User_ID,Cust_name,Gender,Age,recency,frequency,monetary
0,100 Base Layer Ski Pants Women's,Wedze,4.4,836.2629,836.2629,3,2508.7887,156752,2022-05-01,1002903,Sanskriti,F,28,638,1,2508.7887
1,Thermal Underwear Base Layer Top Women's,Wedze,4.5,836.2629,669.6800,2,1339.3600,156753,2022-05-02,1000732,Kartik,F,35,16,2,5106.3100
2,100 Ski Jacket Men's,Wedze,4.6,3347.5629,2511.3000,1,2511.3000,156754,2022-05-03,1001990,Bindu,F,35,636,1,2511.3000
3,Forclaz Trek 500 Merino Wool Hiking Hat Adult,Forclaz,4.6,2091.9129,2091.9129,1,2091.9129,156755,2022-05-04,1001425,Sudevi,M,16,635,1,2091.9129
4,Wedze FR100 Freeride Ski Jacket Women's,Wedze,4.5,9961.4900,5859.7000,3,17579.1000,156756,2022-05-05,1000588,Joni,M,28,633,2,40178.2887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,"MH K100, Category 3 Hiking Sunglasses, Kids'",Quechua,4.6,1087.3929,669.6800,2,1339.3600,157386,2024-01-25,1004682,Vishakha,F,27,4,2,6360.2858
635,Women's Cardio Training Fitness Shoes Mid 120,Domyos,4.4,2929.0129,2092.7500,1,2092.7500,157387,2024-01-26,1004791,Crebagga,F,19,3,1,2092.7500
636,Keepdry 100 Long-Sleeved Soccer Base Layer Top ',Kipsta,4.7,1087.3929,418.5500,3,1255.6500,157388,2024-01-27,1002181,Sweta,F,32,2,2,2929.8500
637,Adult Football Bottoms Essential - Black,Kipsta,4.6,2091.9129,1255.6500,2,2511.3000,157389,2024-01-28,1002109,Gelder,F,34,1,3,28126.5600
638,Boys' Gym Tracksuit Warm Breathable Synthetic ...,Domyos,4.5,2091.9129,1255.6500,1,1255.6500,157390,2024-01-29,1001563,Subhasmita,M,16,0,1,1255.6500

In [8]:
customer_df = df.groupby('User_ID').agg({
    'recency': 'min',
    'frequency': 'sum',
    'monetary': 'sum',
    'Age': 'mean',
    'Gender': 'first',
    'star_rating': 'mean'
}).reset_index()

# Encode the Gender column
customer_df['Gender'] = customer_df['Gender'].map({'M': 1, 'F': 0})

# Display the aggregated data
print(customer_df)

     User_ID  recency  frequency    monetary   Age  Gender  star_rating
0    1000004      315          1   3346.7258  47.0       0     4.100000
1    1000036      202          1    835.4258  27.0       0     4.400000
2    1000053      474          1   2174.7858  33.0       0     4.400000
3    1000058      306          1  13391.9258  33.0       0     4.400000
4    1000071      244          1   5022.6000  33.0       0     4.400000
..       ...      ...        ...         ...   ...     ...          ...
552  1006009      161          1  20090.4000  28.0       1     4.500000
553  1006011      313          1   3346.7258  43.0       0     4.700000
554  1006014      490          1   4603.2129  48.0       0     4.100000
555  1006016      307          9  42428.4135  48.0       0     4.366667
556  1006040      383          4  38503.2516  27.5       0     4.600000

[557 rows x 7 columns]

In [9]:
# Define features and target variable
features = ['recency', 'frequency', 'monetary', 'Age', 'Gender', 'star_rating']
X = customer_df[features]
y = customer_df['monetary']  # Assuming monetary is the target for CLV

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Initialize the model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 1.2922865110730304e-23

In [25]:
# Example customer profile
sample_customer = {
    'recency': 10,       # Days since the last purchase
    'frequency': 1,      # Number of transactions
    'monetary': 15000,    # Total amount spent
    'Age': 30,           # Age of the customer
    'Gender': 1,         # Gender (1 for Male, 0 for Female)
    'star_rating': 4.5   # Average star rating of the products purchased
}

# Convert the dictionary to a DataFrame
sample_df = pd.DataFrame([sample_customer])

# Ensure the order of columns matches the training data
sample_df = sample_df[features]

# Predict CLV for the sample customer
sample_prediction = model.predict(sample_df)

print(f'Predicted Customer Lifetime Value (CLV): {sample_prediction[0]}')

Predicted Customer Lifetime Value (CLV): 14999.999999999998